#对实体类对象Person进行属性配置
person:
  id: 1
  name: Jackson
  hobby: [sing,read,sleep]
  family: [father,mother]
  map: {k1: v1,k2: v2}
  pet: {type: cat, name: tom}
  email: abc@qq.com
  firstName: Li
#  FIRSTNAME: Zhao
#  FIRST_NAME: Liu
#  first-name: zhang
#  first_name: wang


